base_url = "https://frag.dk"
compile_sass = true
build_search_index = true
minify_html = true
theme = "zola-theme-terminimal"
generate_rss = true

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]
## Theme variables
logo_text = "frag.dk"
author = "Kristoffer Søholm"
copyright_html = " "

## Colors
# One of: blue, green, orange, pink, red.
accent_color = "orange"
# One of: blue, dark, green, orange, pink, red.
# background_color = "red"

## Navigation
menu_items = [
    { name = "blog", path = "." },
    { name = "tags", url = "/tags" },
    { name = "archive", url = "/archive" },
    { name = "snippets", path = "snippets" },
    { name = "github", url = "https://github.com/kristoff3r" },
]

enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
use_full_hack_font = true
